#+TITLE: cVim Config File
#+AUTHOR: Samuel Jackson
#+DESCRIPTION: Config for using the cVim plug in.
#+STARTUP: overview hidestars indent num
#+PROPERTY: header-args :results silent :tangle "../configs/.config/cVim/cVimrc"

#+begin_src
" This file has been generated using org tangle. To modify, please see the org file.
#+end_src

* Settings
#+begin_src vimrc
set hud
set smoothscroll
set incsearch
set cncpcompletion
let defaultengine = "google"
let locale = "us"
#+end_src

* Keybindings
** Page scrolling
Basic movement
#+begin_src vimrc
map j scrollDown
map k scrollUp
map h scrollLeft
map l scrollRight
#+end_src

Moving faster.
#+begin_src vimrc
map d scrollPageDown
map u scrollPageUp
map D scrollFullPageDown
map U scrollFullPageUp
#+end_src

Moveing to the edges.
#+begin_src vimrc
map gg scrollToTop
map G scrollToBottom
map 0 scrollToLeft
map $ scrollToRight
#+end_src

** Searches
** Open url
#+begin_src vimcrc
map o :open<Space>
map O :open!<Space>
map <C-o> :open @%
map <A-o> :open! @%
#+end_src
** Tabs
*** Navigation
#+begin_src vimrc
map ^ firstTab
#+end_src
*** Shortcuts
*** Management
#+begin_src vimrc
map < moveTabLeft
map > moveTabRight
map x closeTab
map X lastClosedTab
map <A-p> pinTab
#+end_src

** History navigation
Going backwards and forwards in history
#+begin_src vimrc
map H goBack
map L goForward
#+end_src

Put Open older tab in the background
#+begin_src vimrc
" map <C-h>
" map <C-l>
#+end_src
** Link navigation
** Navigation
** Hinting
** Follow selection
** Yanking (copying)
** Zooming
** Quickmarks/Bookmarks
Working with bookmarks
#+begin_src vimrc
map bc createBookmark
map bo :bookmarks<Space>
map bt :bookmarks!<Space>
map bT :bookmarks&<Space>
#+end_src

** Clearing things away
** Sessions
Session settings.
#+begin_src vimrc
map ss :mksession<Space>
map sd :delsession<Space>
map sr :session<Space>
#+end_src
** Windows
Keybindings for handling which window tabs are a part of.
#+begin_src vimrc
map wa :tabattach<Space>
map wd :tabdetach<CR>
map wo :new<Space>
#+end_src
** Reload
** Macros
** g- and its options
** Settiongs
** Other functionality

* Commands
** Documentation
#+begin_src vimrc
:command doc open! https://github.com/1995eaton/chromium-vim
* Local Variables
The below allows this file to tangle and produce the output RC file whenever the document is saved.

;; Local Variables:
;; eval: (add-hook 'after-save-hook (lambda () (org-babel-tangle)))
;; End:
