#+TITLE: Emacs config file
#+AUTHOR: Samuel Jackson
#+DESCRIPTION: This file defines all my emacs configurations for my doom emacs setup.
#+STARTUP: showall hidestars overview
#+PROPERTY: header-args :results silent :tangle "../configs/.doom.d/config.el"

* File setup
** Initialization
#+BEGIN_SRC elisp :tangle ../configs/.doom.d/init.el
;;; init.el -*- lexical-binding: t; -*-
#+END_SRC
** Packages
#+BEGIN_SRC elisp :tangle ../configs/.doom.d/packages.el
;; -*- no-byte-compile: t; -*-
;;; $DOOMDIR/packages.el
#+END_SRC

** Configuration
#+BEGIN_SRC elisp
;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-
#+END_SRC
* Initialization
** Documentation
#+BEGIN_SRC elisp :tangle no
;; This file controls what Doom modules are enabled and what order they load
;; in. Remember to run 'doom sync' after modifying it!

;; NOTE Press 'SPC h d h' (or 'C-h d h' for non-vim users) to access Doom's
;;      documentation. There you'll find a "Module Index" link where you'll find
;;      a comprehensive list of Doom's modules and what flags they support.

;; NOTE Move your cursor over a module's name (or its flags) and press 'K' (or
;;      'C-c c k' for non-vim users) to view its documentation. This works on
;;      flags as well (those symbols that start with a plus).
;;
;;      Alternatively, press 'gd' (or 'C-c c d') on a module to browse its
;;      directory (for easy access to its source code).
#+END_SRC
** Start
#+BEGIN_SRC elisp :tangle ../configs/.doom.d/init.el
(doom!
;;; Modules to load
#+END_SRC
** Input
#+BEGIN_SRC elisp :tangle ../configs/.doom.d/init.el
       :input
       chinese
       ;;japanese
       ;;layout            ; auie,ctsrnm is the superior home row

#+END_SRC
** Completion
#+BEGIN_SRC elisp :tangle ../configs/.doom.d/init.el
       :completion
       (company +childframe); the ultimate code completion backend
       ;;helm              ; the *other* search engine for love and life
       ;;ido               ; the other *other* search engine...
       ivy               ; a search engine for love and life

#+END_SRC
** UI
#+BEGIN_SRC elisp :tangle ../configs/.doom.d/init.el
       :ui
       deft              ; notational velocity for Emacs
       doom              ; what makes DOOM look the way it does
       doom-dashboard    ; a nifty splash screen for Emacs
       doom-quit         ; DOOM quit-message prompts when you quit Emacs
       fill-column       ; a `fill-column' indicator
       hl-todo           ; highlight TODO/FIXME/NOTE/DEPRECATED/HACK/REVIEW
       ;;hydra
       indent-guides     ; highlighted indent columns
       ligatures         ; ligatures and symbols to make your code pretty again
       minimap           ; show a map of the code on the side
       modeline          ; snazzy, Atom-inspired modeline, plus API
       nav-flash         ; blink cursor line after big motions
       neotree           ; a project drawer, like NERDTree for vim
       ophints           ; highlight the region an operation acts on
       (popup +defaults)   ; tame sudden yet inevitable temporary windows
       ;;tabs              ; a tab bar for Emacs
       treemacs          ; a project drawer, like neotree but cooler
       unicode           ; extended unicode support for various languages
       vc-gutter         ; vcs diff in the fringe
       vi-tilde-fringe   ; fringe tildes to mark beyond EOB
       window-select     ; visually switch windows
       workspaces        ; tab emulation, persistence & separate workspaces
       zen               ; distraction-free coding or writing

#+END_SRC
** Editor tools
#+BEGIN_SRC elisp :tangle ../configs/.doom.d/init.el
       :editor
       (evil +everywhere); come to the dark side, we have cookies
       file-templates    ; auto-snippets for empty files
       fold              ; (nigh) universal code folding
       (format +onsave)  ; automated prettiness
       ;;god               ; run Emacs commands without modifier keys
       ;;lispy             ; vim for lisp, for people who don't like vim
       ;;multiple-cursors  ; editing in many places at once
       ;;objed             ; text object editing for the innocent
       ;;parinfer          ; turn lisp into python, sort of
       rotate-text       ; cycle region at point between text candidates
       snippets          ; my elves. They type so I don't have to
       word-wrap         ; soft wrapping with language-aware indent

#+END_SRC
** Emacs
#+BEGIN_SRC elisp :tangle ../configs/.doom.d/init.el
       :emacs
       (dired            ; making dired pretty [functional]
        +icon)
       electric          ; smarter, keyword-based electric-indent
       ibuffer           ; interactive buffer management
       undo              ; persistent, smarter undo for your inevitable mistakes
       vc                ; version-control and Emacs, sitting in a tree

#+END_SRC
** Terminals
#+BEGIN_SRC elisp :tangle ../configs/.doom.d/init.el
       :term
       eshell            ; the elisp shell that works everywhere
       shell             ; simple shell REPL for Emacs
       term              ; basic terminal emulator for Emacs
       vterm             ; the best terminal emulation in Emacs

#+END_SRC
** Checkers
#+BEGIN_SRC elisp :tangle ../configs/.doom.d/init.el
       :checkers
       syntax            ; tasing you for every semicolon you forget
       spell             ; tasing you for misspelling mispelling
       grammar           ; tasing grammar mistake every you make

#+END_SRC
** Tools
#+BEGIN_SRC elisp :tangle ../configs/.doom.d/init.el
       :tools
       ;;ansible
       ;;debugger          ; FIXME stepping through code, to help you add bugs
       ;;direnv
       (docker +lsp)
       editorconfig      ; let someone else argue about tabs vs spaces
       ein               ; tame Jupyter notebooks with emacs
       (eval +overlay)     ; run code, run (also, repls)
       ;;gist              ; interacting with github gists
       lookup              ; navigate your code and its documentation
       lsp
       magit             ; a git porcelain for Emacs
       make              ; run make tasks from Emacs
       pass              ; password manager for nerds
       pdf               ; pdf enhancements
       ;;prodigy           ; FIXME managing external services & code builders
       rgb               ; creating color strings
       ;;taskrunner        ; taskrunner for all your projects
       ;;terraform         ; infrastructure as code
       tmux              ; an API for interacting with tmux
       ;;upload            ; map local to remote projects via ssh/ftp

#+END_SRC
** OS
#+BEGIN_SRC elisp :tangle ../configs/.doom.d/init.el
       :os
       (:if IS-MAC macos)  ; improve compatibility with macOS
       tty               ; improve the terminal Emacs experience

#+END_SRC
** Programming Languages
#+BEGIN_SRC elisp :tangle ../configs/.doom.d/init.el
       :lang
       ;;agda              ; types of types of types of types...
       cc                ; C/C++/Obj-C madness
       clojure           ; java with a lisp
       common-lisp       ; if you've seen one lisp, you've seen them all
       ;;coq               ; proofs-as-programs
       ;;crystal           ; ruby at the speed of c
       ;;csharp            ; unity, .NET, and mono shenanigans
       ;;data              ; config/data formats
       ;;(dart +flutter)   ; paint ui and not much else
       elixir            ; erlang done right
       elm               ; care for a cup of TEA?
       emacs-lisp        ; drown in parentheses
       erlang            ; an elegant language for a more civilized age
       ess               ; emacs speaks statistics
       ;;faust             ; dsp, but you get to keep your soul
       ;;fsharp            ; ML stands for Microsoft's Language
       ;;fstar             ; (dependent) types and (monadic) effects and Z3
       ;;gdscript          ; the language you waited for
       (go +lsp)         ; the hipster dialect
       (haskell +dante)  ; a language that's lazier than I am
       ;;hy                ; readability of scheme w/ speed of python
       ;;idris             ; a language you can depend on
       json              ; At least it ain't XML
       (java +meghanada) ; the poster child for carpal tunnel syndrome
       (javascript +lsp) ; all(hope(abandon(ye(who(enter(here))))))
       julia             ; a better, faster MATLAB
       kotlin            ; a better, slicker Java(Script)
       (latex +lsp       ; writing papers in Emacs has never been so fun
              +latexmk
              +cdlatex
              +fold)
       ;;lean
       ;;factor
       ledger            ; an accounting system in Emacs
       lua               ; one-based indices? one-based indices
       (markdown +grip)  ; writing docs for people to ignore
       ;;nim               ; python + lisp at the speed of c
       ;;nix               ; I hereby declare "nix geht mehr!"
       ;;ocaml             ; an objective camel
       (org +brain       ; organize your plain life in plain text
            +dragndrop
            +gnuplot
            +ipython
            +journal
            +jupyter
            +noter
            +pandoc
            +pomodoro
            +present
            +pretty
            +roam2)
       ;;php               ; perl's insecure younger brother
       plantuml          ; diagrams for confusing people more
       purescript        ; javascript, but functional
       python            ; beautiful is better than ugly
       ;;qt                ; the 'cutest' gui framework ever
       racket            ; a DSL for DSLs
       ;;raku              ; the artist formerly known as perl6
       rest              ; Emacs as a REST client
       rst               ; ReST in peace
       (ruby +rails      ; 1.step {|i| p "Ruby is #{i.even? ? 'love' : 'life'}"}
             +rvm
             +rbenv
             +lsp)
       rust              ; Fe2O3.unwrap().unwrap().unwrap().unwrap()
       scala             ; java, but good
       scheme            ; a fully conniving family of lisps
       sh                ; she sells {ba,z,fi}sh shells on the C xor
       ;;sml
       ;;solidity          ; do you need a blockchain? No.
       ;;swift             ; who asked for emoji variables?
       ;;terra             ; Earth and Moon in alignment for performance.
       web               ; the tubes
       yaml              ; JSON, but readable

#+END_SRC
** Email
#+BEGIN_SRC elisp :tangle ../configs/.doom.d/init.el
       :email
       (mu4e +gmail)
       ;;notmuch
       (wanderlust +gmail)

#+END_SRC
** App
#+BEGIN_SRC elisp :tangle ../configs/.doom.d/init.el
       :app
       calendar
       irc               ; how neckbeards socialize
       (rss +org)        ; emacs as an RSS reader
       twitter           ; twitter client https://twitter.com/vnought

#+END_SRC
** Config
#+BEGIN_SRC elisp :tangle ../configs/.doom.d/init.el
       :config
       ;;literate
       (default +bindings +smartparens)
#+END_SRC
** End section
#+BEGIN_SRC elisp :tangle ../configs/.doom.d/init.el
)
#+END_SRC

* Configuration
#+BEGIN_SRC elisp
;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-
#+END_SRC
** Documentation
*** Macro documentation
#+BEGIN_SRC elisp :tangle no
;; Here are some additional functions/macros that could help you configure Doom:
;;
;; - `load!' for loading external *.el files relative to this one
;; - `use-package!' for configuring packages
;; - `after!' for running code after a package has loaded
;; - `add-load-path!' for adding directories to the `load-path', relative to
;;   this file. Emacs searches the `load-path' when you load packages with
;;   `require' or `use-package'.
;; - `map!' for binding new keys
;;
;; To get information about any of these functions/macros, move the cursor over
;; the highlighted symbol at press 'K' (non-evil users must press 'C-c c k').
;; This will open documentation for it, including demos of how they are used.
;;
;; You can also try 'gd' (or 'C-c c d') to jump to their definition and see how
;; they are implemented.
#+END_SRC

*** Packages documentation
#+BEGIN_SRC elisp :tangle no
;; To install a package with Doom you must declare them here and run 'doom sync'
;; on the command line, then restart Emacs for the changes to take effect -- or
;; use 'M-x doom/reload'.


;; To install SOME-PACKAGE from MELPA, ELPA or emacsmirror:
;(package! some-package)

;; To install a package directly from a remote git repo, you must specify a
;; `:recipe'. You'll find documentation on what `:recipe' accepts here:
;; https://github.com/raxod502/straight.el#the-recipe-format
;(package! another-package
;  :recipe (:host github :repo "username/repo"))

;; If the package you are trying to install does not contain a PACKAGENAME.el
;; file, or is located in a subdirectory of the repo, you'll need to specify
;; `:files' in the `:recipe':
;(package! this-package
;  :recipe (:host github :repo "username/repo"
;           :files ("some-file.el" "src/lisp/*.el")))

;; If you'd like to disable a package included with Doom, you can do so here
;; with the `:disable' property:
;(package! builtin-package :disable t)

;; You can override the recipe of a built in package without having to specify
;; all the properties for `:recipe'. These will inherit the rest of its recipe
;; from Doom or MELPA/ELPA/Emacsmirror:
;(package! builtin-package :recipe (:nonrecursive t))
;(package! builtin-package-2 :recipe (:repo "myfork/package"))

;; Specify a `:branch' to install a package from a particular branch or tag.
;; This is required for some packages whose default branch isn't 'master' (which
;; our package manager can't deal with; see raxod502/straight.el#279)
;(package! builtin-package :recipe (:branch "develop"))

;; Use `:pin' to specify a particular commit to install.
;(package! builtin-package :pin "1a2b3c4d5e")


;; Doom's packages are pinned to a specific commit and updated from release to
;; release. The `unpin!' macro allows you to unpin single packages...
;(unpin! pinned-package)
;; ...or multiple packages
;(unpin! pinned-package another-pinned-package)
;; ...Or *all* packages (NOT RECOMMENDED; will likely break things)
;(unpin! t)

#+END_SRC
** Personal Identification
#+BEGIN_SRC elisp
;; Some functionality uses this to identify you, e.g. GPG configuration, email
;; clients, file templates and snippets.
(setq user-full-name "Samuel Jackson"
      user-mail-address "dsiq3g@gmail.com")
#+END_SRC

** Fonts and language
*** Chinese support
In order for Chinese text to be displayed correctly, some modes needs to be turned on to allow for the unique characteristics of the symbolic language.
#+BEGIN_SRC elisp
(defun chinese-text-support ()
  "Turn on modes to support chinese text in the buffer. May cause other text to change characteristics as well."
  (interactive)
  (variable-pitch-mode))
#+END_SRC

** Basic Emacs settings
*** Fonts
#+BEGIN_SRC elisp
;; Doom exposes five (optional) variables for controlling fonts in Doom. Here
;; are the three important ones:
;;
;; + `doom-font'
;; + `doom-variable-pitch-font'
;; + `doom-big-font' -- used for `doom-big-font-mode'; use this for
;;   presentations or streaming.
;;
;; They all accept either a font-spec, font string ("Input Mono-12"), or xlfd
;; font string. You generally only need these two:
;; (setq doom-font (font-spec :family "monospace" :size 12 :weight 'semi-light)
;;       doom-variable-pitch-font (font-spec :family "sans" :size 13))
#+END_SRC

*** Custom settings file
#+BEGIN_SRC elisp
(setq custom-file (expand-file-name ".custom.el" doom-private-dir))
(when (file-exists-p custom-file) (load custom-file))
#+END_SRC

*** Theming
#+BEGIN_SRC elisp :tangle ../configs/.doom.d/packages.el
;; Themes
(package! dracula-theme)
(package! theme-magic)
#+END_SRC

There are two ways to load a theme. Both assume the theme is installed and available. You can either set `doom-theme' or manually load a theme with the `load-theme' function.
#+BEGIN_SRC elisp
(setq doom-theme (if (display-graphic-p)'doom-one 'doom-dracula))
#+END_SRC

*** Line numbering
#+BEGIN_SRC elisp
;; This determines the style of line numbers in effect. If set to `nil', line
;; numbers are disabled. For relative line numbers, set this to `relative'.
(setq display-line-numbers-type t)
#+END_SRC

*** Undo
#+BEGIN_SRC elisp
;; Let the undo buffer use up to 100Mb
(setq undo-limit 100000000)
#+END_SRC

*** Windows
#+BEGIN_SRC elisp
;; Resize all windows when a new one comes in so they have
;; equal space.
(setq-default window-combination-resize t
;; changes the cursor to be the size of a gliph in the buffer.
              x-stretch-cursor t)

;; (setq-default left-margin-width 1)
;; (set-window-buffer nil (current-buffer))
#+END_SRC
*** Clipboard
Prevents system clipboard from being accidentially overwritten. Must now write to register "+ to write to system clipboard.
#+BEGIN_SRC elisp
;; Some paste related settings.
(setq save-interprogram-paste-before-kill t
      select-enable-clipboard nil)
#+END_SRC

In order to provide copy and paste functionality directly from the keyboard, I need to capture the inputs and make functions that force the register that corresponds with the clipboard to be used (the + register).

First, I need to set up the wrapper functions. The thing to note is that these are just copies of the underlying function's header but they pass in the register's ascii number. Inorder to get the ascii number of a character, we simply need to put a '?' before it.
#+BEGIN_SRC elisp
(evil-define-operator evil-copy-to-clipboard (beg end &optional type _ handler)
  "Saves the characters in motion into they system clipboard through the '+' register"
  :move-point nil
  :repeat nil
  (interactive "<R><x><y>")
  (evil-yank beg end type ?+ handler))
#+END_SRC

And here is the paste function.
#+BEGIN_SRC elisp
(evil-define-command evil-paste-from-clipboard
  (count &optional _ handler)
  "Pastes the latest yanked text behind point.
The return value is the yanked text."
  :suppress-operator t
  (interactive "*P<x>")
  (evil-paste-before count ?+ handler))
#+END_SRC

Finally we need to create universal keybindings to these functions so they can be called from anywhere.
#+BEGIN_SRC elisp
(map! :desc "Paste from clipboard" :nvieomg "s-v" #'evil-paste-from-clipboard
      :desc "Copy to clipboard"    :nvieomg "s-c" #'evil-copy-to-clipboard)
#+END_SRC

*** Scrolling
#+BEGIN_SRC elisp
;; leave some space at the bottom while scrolling down so the
;; cursor isn't hugging the bottom edge.
(setq scroll-margin 2)
#+END_SRC

*** Scratch buffer
The scratch buffer is always present as an area to experiement or take a quick note without it needing to be a part of a file. In doom, this scratch buffer has a default mode of Fundemental which is both useless and not something I need for experimentation. In fact, I think it's meant for just writing text and notes. I want the scratch buffer to be a place to write some elislp code so I can set things on a whim while working in other non-elisp buffers.
#+BEGIN_SRC elisp
(setq initial-major-mode 'emacs-lisp-mode)

(setq initial-scratch-message "\
;; Welcome to the scratch buffer.

")
#+END_SRC

*** Tab bar mode
TODO Add commentary
#+BEGIN_SRC elisp
(setq tab-bar-show 1)
(setq tab-bar-tab-name-function #'tab-bar-tab-name-current)
(setq tab-bar-format '(tab-bar-format-tabs tab-bar-separator tab-bar-format-align-right tab-bar-format-global))
(set-face-attribute 'tab-bar nil :inherit 'tab-bar-tab :foreground nil :background nil)
(map! :n "M->" #'tab-next
      :n "M-<" #'tab-previous)
#+END_SRC
*** Directory navigation
#+BEGIN_SRC elisp :tangle ../configs/.doom.d/packages.el
;; directory management
(package! dired-sidebar)
(package! dired+)
(package! dired-subtree)
#+END_SRC

#+BEGIN_SRC elisp
(defun dired-turn-off-file-info ()
  "Turns off the file info in dired mode"
  (interactive)
  (dired-hide-details-mode t))
(add-hook! 'dired-mode-hook #'dired-turn-off-file-info)

(map! :map dired-mode-map
      :leader
      :desc "toggle dired file info"
      :n "t d" #'dired-hide-details-mode)
#+END_SRC
** Adding standard vim functionality
I don't remember why I wrote this line in the first place but it seems useful for later
#+BEGIN_SRC elisp
(defun smart-open-line-above ()
  "Insert an empty line above the current line.
Position the cursor at it's beginning, according to the current mode."
  (interactive)
  (move-beginning-of-line nil)
  (newline-and-indent)
  (forward-line -1)
  (indent-according-to-mode))
#+END_SRC

** Managing files
*** Sidebar file explorer
#+BEGIN_SRC elisp
(map! :n "C-n" #'dired-sidebar-toggle-sidebar)
#+END_SRC

*** Projectile
#+BEGIN_SRC elisp
(after! projectile
  (setq projectile-track-known-projects-automatically nil))
#+END_SRC

*** Snippets
#+BEGIN_SRC elisp
;; enables nested snippets
(setq yas-triggers-in-field t)
#+END_SRC

** General utility package settings
These aren't file or use case specific changes but instead things that can apply over many different major modes and situations.
*** Sub-word movement
#+BEGIN_SRC elisp
;; Makes it so movement keys stop at camlecase sub words.
(global-subword-mode 1)
#+END_SRC

*** Case insensitive search
=case-fold-search= is a variable that turns case sensitivity on and off. It is set per buffer. Since I like case sensitivity, I'm setting the default value so that new buffers use case sensitive searches.
#+BEGIN_SRC elisp
;; Make searches case sensitive
(setq-default case-fold-search nil)
#+END_SRC

*** Which key
#+BEGIN_SRC elisp :tangle ../configs/.doom.d/packages.el
(package! discover-my-major)
#+END_SRC

#+BEGIN_SRC elisp
(map! :n "g /"   #'which-key-show-top-level
      :n "g C-/" #'which-key-show-full-major-mode
      :n "g ?"   #'which-key-show-full-major-mode
      :n "g M-/" #'which-key-show-minor-mode-keymap)
(setq which-key-idle-delay 0.5)
#+END_SRC

*** Write good mode
#+BEGIN_SRC elisp
(remove-hook! (org-mode markdown-mode rst-mode asciidoc-mode latex-mode) #'writegood-mode)
(add-hook 'writegood-mode-hook 'writegood-passive-voice-turn-off)
(map! :leader
      :desc "Write good mode"
      "t W" #'writegood-mode)
#+END_SRC

*** Flycheck mode
#+BEGIN_SRC elisp
;; Disable flycheck mode on load. Can be re-enabled in a buffer with SPC t f
(remove-hook! (doom-first-buffer) #'global-flycheck-mode)
#+END_SRC

*** Evil mode
**** Evil settings
#+BEGIN_SRC elisp
;; Make undo revert smaller sections of text instead of all text
;; added while in insert mode.
(setq evil-want-fine-undo t)
#+END_SRC
**** Evil snipe mode
***** Snipe mode off by default
I get really annoyed by snipe mode since I often use 's' for deleting text. Therefore I use the workaround below to turn off evil snipe mode by default since I really don't want it.
#+BEGIN_SRC elisp
; Remove default snipe mode
(remove-hook! (doom-first-input) 'evil-snipe-mode)
; There can be problems between snipe mode and magit mode.
(add-hook 'magit-mode-hook 'turn-off-evil-snipe-override-mode)
#+END_SRC

***** Settings
Some settings for when snipe mode is on.
#+BEGIN_SRC elisp
(setq evil-snipe-scope 'whole-visible
      evil-snipe-repeat-scope 'whole-visible)
#+END_SRC

***** New keybinding
This allows you to toggle evil snipe mode on and off (though it's still off by default)
#+BEGIN_SRC elisp
(defun toggle-and-activate-evil-snipe-mode ()
  "Toggles evil-snipe-mode on and off then activates the
mode map since otherwise it requires forcing the normal mode state to be activated."
  (interactive)
  (evil-snipe-local-mode)
  (evil-force-normal-state))

(map! :leader
      :desc "Evil snipe mode"
      "t S" #'toggle-and-activate-evil-snipe-mode)
#+END_SRC
*** VLF (Very Large Files)
VLF if a package for lazy loading enormous files that would normally take forever to load. The package needs to be first added but disabled so that it doesn't hamper load times. This formula was pulled from [[https://tecosaur.github.io/emacs-config/config.html#very-large-files][this]] legendary config.
#+BEGIN_SRC elisp :tangle ../configs/.doom.d/packages.el
;; [[file:~/.config/doom/config.org::*Very large files][Very large files:1]]
(package! vlf :recipe (:host github :repo "m00natic/vlfi"))
#+END_SRC

Then setup the package later.
#+BEGIN_SRC elisp
(use-package! vlf-setup
  :defer-incrementally vlf-tune vlf-base vlf-write vlf-search vlf-occur vlf-follow vlf-ediff vlf)
#+END_SRC

*** Colored info
#+BEGIN_SRC elisp :tangle ../configs/.doom.d/packages.el
(package! info-colors)
#+END_SRC

#+BEGIN_SRC elisp
(use-package! info-colors
  :commands (info-colors-fontify-node))
(add-hook 'info-selection-hook 'info-colors-fontify-node)
#+END_SRC

*** R data frames
This allows emacs to handle R style dataframes. This makes some data handling easier in various files.
#+BEGIN_SRC elisp :tangle ../configs/.doom.d/packages.el
(package! ess-view)
#+END_SRC

*** Dictionary
#+BEGIN_SRC elisp
;; Set the correct dictionary for spell check.
(setq ispell-dictionary "en")
#+END_SRC

** Independent or external programs
*** Discord integration
#+BEGIN_SRC elisp :tangle ../configs/.doom.d/packages.el
(package! elcord)
#+END_SRC

*** Speed reading
#+BEGIN_SRC elisp :tangle ../configs/.doom.d/packages.el
(package! spray)
#+END_SRC

*** Presentations
**** Key cast
#+BEGIN_SRC elisp :tangle ../configs/.doom.d/packages.el
(package! keycast)
#+END_SRC

#+BEGIN_SRC elisp
(use-package! keycast
  :commands keycast-mode
  :config
  (define-minor-mode keycast-mode
    "Show current command and its key bining in the mode line."
    :global t
    (if keycast-mode
        (progn
          (add-hook 'pre-command-hook 'keycast--update t)
          (add-to-list 'global-mode-string '("" mode-line-keycast " ")))
      (remove-hook 'pre-command-hook 'keycast--update)
      (setq global-mode-string (remove '("" mode-line-keycast " ") global-mode-string))))
  (custom-set-faces!
    ('keycast-command :inherit doom-modeline-debug :height 0.9)
    ('keycast-key :inherit custom-modified :height 1.1 :weight bold)))
#+END_SRC

**** Gif Screenshot
#+BEGIN_SRC elisp :tangle ../configs/.doom.d/packages.el
(package! gif-screencast)
#+END_SRC

#+BEGIN_SRC elisp
(use-package! gif-screencast
  :commands gif-screencast-mode
  :config
  (map! :map gif-screencast-mode-map
        :g "<f8>" #'gif-screencast-toggle-pause
        :g "<f9>" #'gif-screencast-stop)
  (setq gif-screencast-program "maim"
        gif-screencast-args '("--quality" "3" "-1" ,(string-trim-right (shell-command-to-string "xdotool getactivewindow")))
        gif-screencast-optimize-args '("--batch" "--optimize=3" "--usecolormap=/tmp/doom-color-theme"))
  (defun gif-screencast-write-colormap ()
    (f-write-text
     (replace-regexp-in-string "\n+" "\n"
                               (mapconcat (lambda (c) (if (listp (cdr c))) (cadr c)))
                               'utf-8
                               "/tmp/doom-color-theme")))
  (gif-screencast-write-colormap)
  (add-hook 'doom-load-theme-hook #'gif-screencast-write-colormap))
#+END_SRC

**** Command log mode
#+BEGIN_SRC elisp :tangle ../configs/.doom.d/packages.el
(package! command-log-mode)
#+END_SRC

** Mode/package settings
*** Guix
#+BEGIN_SRC elisp :tangle ../configs/.doom.d/packages.el
(package! guix)
#+END_SRC

*** Elisp-shell
#+BEGIN_SRC elisp
(setq eshell-aliases-file "~/.doom.d/.eshell-aliases")
#+END_SRC
**** Elisp shell aliases
#+BEGIN_SRC elisp :tangle ../configs/.doom.d/.eshell-aliases
#+END_SRC
*** Mode line
Adds details to the emacs mode line at the bottom of the page. Although several of the values can be referenced elsewhere on a given page, seeing them there is often just convenient and it uses space that would otherwise go unused.
**** Date and time
#+BEGIN_SRC elisp
;; Add useful data to the mode line.
(setq display-time-day-and-date t)
(display-time-mode 1)
#+END_SRC

**** Battery
For the battery, I don't want it to appear in the the mode line if there is no battery present.

Since the following functions require the battery package, I need to wrap it in ~use-package~ to make sure all the definitions are loaded.
#+BEGIN_SRC elisp
(use-package! battery :config
#+END_SRC

Sadly, there are no default functions for finding if a battery is present so I'll start by writing my own based off of the ~battery~ function in [[https://github.com/emacs-mirror/emacs/blob/3af9e84ff59811734dcbb5d55e04e1fdb7051e77/lisp/battery.el#L219][battery.el]].
#+BEGIN_SRC elisp
    (defun battery-p ()
        "returns t if a battery is present for the system and nil if one is not."
        (and battery-status-function
             battery-echo-area-format
             (string-match-p "^Power N/A"
                             (battery-format
                                     battery-echo-area-format
                                     (funcall battery-status-function)))
             t))
#+END_SRC

If a battery source is detected, then show the batter level in the mode bar.
#+BEGIN_SRC elisp
    (unless (battery-p) (display-battery-mode 1))
#+END_SRC

Finally, close the battery package wrapper.
#+BEGIN_SRC elisp
)
#+END_SRC

**** Encoding format
#+BEGIN_SRC elsip
(defun doom-modeline-conditional-buffer-encoding ()
  "We expect the encoding to be LF UTF-8,
so only show the modeline when this is not the case"
  (setq-local doom-modeline-buffer-encoding
              (if (and
                       ; Checking for UTF-8
                       (memq
                        (plist-get (coding-system-plist buffer-file-coding-system) :category)
                        '(coding-category-utf-8))
                       ; Checking for LF line ending
                       (not
                        (memq (coding-system-eol-type buffer-file-coding-system) '(1 2))))
                t nil)))
(add-hook 'after-change-major-mode-hook #'doom-modeline-conditional-buffer-encoding)
#+END_SRC

*** Web mode
#+BEGIN_SRC elisp
(setq web-mode-script-padding standard-indent)
(setq web-mode-style-padding standard-indent)
(setq web-mode-block-padding standard-indent)
(setq web-mode-part-padding standard-indent)
#+END_SRC

*** Org mode
**** Org add-on packages
#+BEGIN_SRC elisp :tangle ../configs/.doom.d/packages.el
;; Org mode related stuff
(package! org-reverse-datetree)
;(package! ox-gfm) ; Causing problems with pandoc at the moment.
(package! org-ref)
(package! org-chef)
(package! org-super-agenda)
(package! org-fragtog)
(package! org-pretty-tags)
#+END_SRC
**** Standard Org settings
If you use `org' and don't want your org files in the default location below, change `org-directory'. It must be set before org loads!
#+BEGIN_SRC elisp
(setq org-directory "~/org")
(setq org-archive-location "archive/%s_archive::")
#+END_SRC
***** Font support
In org mode I like to be able to write in different fonts and languages (such as chinese) so I'm turning on variable pitch font support. Without it, lots of text starts to overlap.
#+BEGIN_SRC elisp :tangle no
(add-hook 'org-mode-hook #'chinese-text-support)
#+END_SRC

***** Bable
Several languages require LSPs or other backend code to be configured for bable to use them so they are configured here.
****** Clojure
#+BEGIN_SRC elisp :tangle ../configs/.doom.d/packages.el
;; Clojure related packages
(package! clojure-mode)
(package! clojure-mode-extra-font-locking)
(package! clj-refactor)
(package! cider)
#+END_SRC

#+BEGIN_SRC elisp
(setq org-bable-clojure-backend 'cider)
#+END_SRC
***** Org mode keybindings
#+BEGIN_SRC elisp
;; Use keybinding g b to "go back" to previous location when a link is followed.
;; Use keybinding g m to "go mark" the current location so it can be returned to later.
(map! :after org
    :map org-mode-map
    :n  "g m" #'org-mark-ring-push
    :n  "g b" #'org-mark-ring-goto
    :nv "g j" #'evil-next-visual-line
    :nv "g k" #'evil-previous-visual-line
    :nv "g J" #'org-forward-element
    :nv "g K" #'org-backward-element)
#+END_SRC
***** Shortcut to open org files
This shortcut opens the org directory and allows a user to select a file. If the file doesn't yet exist then it is created. This is useful when I want to open some information on something that I've been tracking but don't have another shortcut to it saved somewhere.
#+BEGIN_SRC elisp
(setq org-default-extension ".org")
(defun org-open-org-file (file)
  "Opens an org file in the default org folder.
if no org extension is given then it will be automatically appended."
  (interactive
   (list (directory-file-name
          (read-file-name "Choose org file:" org-directory))))

  ; Check for if the file:
  ; * Already exists (and is not a directory)
  ; * Has an org extension
  ; If neither of these cases is valid then automatically append an org extension
  ; to the provided file name.
  (let ((input-file-extension (concat "." (file-name-extension file)))
        (valid-org-extension-regex-list
         (mapcar 'car
                 (seq-filter
                  (lambda (mode-pairs) (eq 'org-mode (cdr mode-pairs)))
                  auto-mode-alist))))
    (unless
        (or (and (file-exists-p file)
                 (not (file-directory-p file)))
            (and input-file-extension
                 ; check the input
                 (eval (cons 'or (mapcar (lambda (extension-regex)
                           (string-match-p extension-regex input-file-extension))
                         valid-org-extension-regex-list)))))
      (setq file (concat file org-default-extension)))) ; Otherwise set file to have an org extension)

    ; If, after the above checks, the file name still points to a directory, then
    ; throw an error since it can't be opened at that point.
    (if (file-directory-p file)
        (error "The provided file is a directory %s" file)
      (find-file file)
      (org-mode)))

(map! :leader
      :desc "Find org file"
      "f o" #'org-open-org-file)
#+END_SRC

**** Org Roam
#+BEGIN_SRC elisp
(setq org-roam-directory "~/roam")
(setq org-roam-v2-ack t)
#+END_SRC

**** Timers and clock
#+BEGIN_SRC elisp
(setq org-clock-persist 'history)
(org-clock-persistence-insinuate)
#+END_SRC
**** Org Agenda
***** Limiting files
To set specific files as being "agenda" files, you can use =org-agenda-files= however I've found I like putting schedule markers in various files around my org setup.
#+BEGIN_SRC elisp :tangle no
(setq org-agenda-files (list "~/org/work.org"
                             "~/org/todo.org"))
#+END_SRC

**** Pomodoro
***** Begin "after! org"
All these settings have to be made after org loads so they're wrapped in an =(after! org ...)= macro.
#+BEGIN_SRC elisp
(after! org
#+END_SRC
***** Work length
#+BEGIN_SRC elisp
(setq org-pomodoro-length 25
    org-pomodoro-short-break-length 5
    org-pomodoro-long-break-length 15)
#+END_SRC
***** Sounds to play
#+BEGIN_SRC elisp
(setq org-pomodoro-play-sounds t
    ;; org-pomodoro-start-sound-p f
    ;; org-pomodoro-ticking-sound-p f
    org-pomodoro-killed-sound-p t
    org-pomodoro-finished-sound-p t
    org-pomodoro-short-break-sound-p t
    org-pomodoro-long-break-sound-p t)
#+END_SRC

***** Sounds to use
If I decide to find sound files I like more than the defaults, then I can put them here.
#+BEGIN_SRC elisp :tangle no
(setq ;org-pomodoro-start-sound ()
      ;org-pomodoro-ticking-sound ()
      org-pomodoro-killed-sound ()
      org-pomodoro-finished-sound ()
      org-pomodoro-short-break-sound ()
      org-pomodoro-long-break-sound ())
#+END_SRC
***** End of "after! org"
#+BEGIN_SRC elisp
)
#+END_SRC
**** Org Capture
***** Settings
#+BEGIN_SRC elisp
; Set default file for newly captured notes
(after! org (setq org-default-notes-file (concat org-directory "/inbox.org")))
#+END_SRC

***** Org template
****** Anxiety/Worry template
#+BEGIN_SRC elisp
(defun get-current-timestamp ()
  "returns a string timestamp in the format [yyyy-mm-dd day hh:mm]"
  (let ((time (current-time))
         (fmt (cdr org-time-stamp-formats)))
    (setq fmt (concat "[" (substring fmt 1 -1) "]"))
    (format-time-string fmt time)))

(defun worry-template ()
  "Produces a template that is meant to"
  (let ((topic (read-string "My goal is to understand why I'm worried about: ")))
    (concat
     "* " topic "\n"
     "** Intake\nDate/time: " (get-current-timestamp) "\n"
     "My goal is to understand why I'm worried about " topic ".\n"
     "** Investigation\n"
     "*** Triggers\n"
     "Pick the triggers below that apply to this issue.\n"
     "- [ ] Trying to make everyone happy\n"
     "- [ ] Perfectionism\n"
     "- [ ] I'm-not-doing-my-job panic attack\n"
     "- [ ] Imposter syndrome\n"
     "- [ ] Compare and despair\n"
     "- [ ] Other (add to master list if needed)\n\n"
     "This worry involves:\n"
     "- [ ] someone else's perception of me.\n"
     "- [ ] my perception of myself.\n\n"
     "Real world events I'm reacting to, and duration (secs/mins/hrs/etc.):\n\n"
     "Am I doing something that feels too difficult?\n\n"
     "*** Five whys\n"
     "- Q1) Why am I worried about ...\n"
     "- Q2) Why ...\n"
     "- Q3) Why ...\n"
     "- Q4) Why ...\n"
     "- Q5) Why ...\n\n"
     "** Resolution\n"
     "1. Do I /want/ to take action? If so, what is my goal? _____\n"
     "2. Do I /have/ to take action? If so, what is my goal? _____\n"
     "3. What happens if I do nothing? _____\n"
     "4. What is the worst thing I can imagine happening? _____\n"
     "5. What do I think is the most likely to happen? _____\n"
     "6. Is there an opportunity to Think Big here? What would it look like if this issue were resolved far better than I ever imagined? _____\n"
     "7. The next concrete step I will take is _____\n"
     "8. Is there a step I can add to a personal checklist to reduce the chance this worry happens again? _____\n")))

(after! org
  (add-to-list 'org-capture-templates
                '("w" "Worry Capture" entry (file "worries.org") (function worry-template) :prepend t :immediate-finish t)))
#+END_SRC

****** Test checklist template
#+BEGIN_SRC elisp
(after! org
  (add-to-list 'org-capture-templates
                '("l" "Test Capture" checkitem (file+olp+datetree org-default-notes-file) "[ ]")))
#+END_SRC
****** Example template code
Example of org capture templates and how everything is setup.
pulled from https://github.com/hlissner/doom-emacs/blob/develop/modules/lang/org/config.el
#+BEGIN_SRC elisp :tangle no
(after! org
  (setq org-capture-templates '(
    ("t" "Todo" entry () "" :prepend t)
    ("k" "Kudos" entry () "" :prepend t)
    ("f" "Followup" entry () "" :prepend t)
    ("p" "Personal" entry () "" :prepend t)
    ("P" "Project" entry () "" :prepend t)
    ("j" "Journal" entry () "" :prepend t)
  )))
'(
  ("t" "Personal todo" entry (file+headline +org-capture-todo-file "Inbox") "* [ ] %?\n%i\n%a" :prepend t)
          ("n" "Personal notes" entry (file+headline +org-capture-notes-file "Inbox") "* %u %?\n%i\n%a" :prepend t)
          ("j" "Journal" entry (file+olp+datetree +org-capture-journal-file)
           "* %U %?\n%i\n%a" :prepend t)

          ;; Will use {project-root}/{todo,notes,changelog}.org, unless a
          ;; {todo,notes,changelog}.org file is found in a parent directory.
          ;; Uses the basename from `+org-capture-todo-file',
          ;; `+org-capture-changelog-file' and `+org-capture-notes-file'.
          ("p" "Templates for projects")
          ("pt" "Project-local todo" entry  ; {project-root}/todo.org
           (file+headline +org-capture-project-todo-file "Inbox")
           "* TODO %?\n%i\n%a" :prepend t)
          ("pn" "Project-local notes" entry  ; {project-root}/notes.org
           (file+headline +org-capture-project-notes-file "Inbox")
           "* %U %?\n%i\n%a" :prepend t)
          ("pc" "Project-local changelog" entry  ; {project-root}/changelog.org
           (file+headline +org-capture-project-changelog-file "Unreleased")
           "* %U %?\n%i\n%a" :prepend t)

          ;; Will use {org-directory}/{+org-capture-projects-file} and store
          ;; these under {ProjectName}/{Tasks,Notes,Changelog} headings. They
          ;; support `:parents' to specify what headings to put them under, e.g.
          ;; :parents ("Projects")
          ("o" "Centralized templates for projects")
          ("ot" "Project todo" entry
           (function +org-capture-central-project-todo-file)
           "* TODO %?\n %i\n %a"
           :heading "Tasks"
           :prepend nil)
          ("on" "Project notes" entry
           (function +org-capture-central-project-notes-file)
           "* %U %?\n %i\n %a"
           :heading "Notes"
           :prepend t)
          ("oc" "Project changelog" entry
           (function +org-capture-central-project-changelog-file)
           "* %U %?\n %i\n %a"
           :heading "Changelog"
           :prepend t)))
#+END_SRC
**** Org Chef
Org chef is a package for saving cooking recipes from sites like [[allrecipes.com][allrecipies]] in org mode for future reference and use.
#+BEGIN_SRC elisp
(use-package! org-chef
  :commands (org-chef-insert-recipe org-chef-get-recipe-from-url))
#+END_SRC

*** Systemd
*** E-book reader
**** Packages
#+BEGIN_SRC elisp :tangle ../configs/.doom.d/packages.el
;; e-reader
(package! calibredb)
(package! nov)
#+END_SRC

**** Settings
#+BEGIN_SRC elisp
(use-package! nov ; Novel reading
  :mode ("\\.epub\\'" . nov-mode)
  :config
  (map! :map nov-mode-map
        :n "RET" #'nov-scroll-up)
  (defun doom-modeline-segment--nov-info ()
    (concat
     " " (propertize
          (cdr (assoc 'creator nov-metadata))
          'face
          'doom-modeline-project-parent-dir)
     " " (cdr (assoc 'title nov-metadata))
     " " (propertize
          (format "%d/%d" (1+ nov-documents-index) (length nov-documents))
          'face
          'doom-modeline-info)))
  (advice-add 'nov-render-title :override #'ignore)
  (defun +nov-mode-setup ()
    (require 'visual-fill-column nil t)
    (setq-local visual-fill-column-center-text t
                visual-fill-column-width 80
                nov-text-width 80)
    (visual-fill-column-mode 1)
    (hl-line-mode -1)
    (add-to-list '+lookup-definition-functions #'+lookup/dictionary-definition)

    (setq-local mode-line-format
                `((:eval (doom-modeline-segment--workspace-name))
                  (:eval (doom-modeline-segment--window-number))
                  (:eval (doom-modeline-segment--nov-info))
                  ,(propertize " "
                               'face (if (doom-modeline--active) 'mode-line 'mode-line-inactive)
                               'display `((space :align-to
                                                 (-
                                                  (+ right right-fringe right-margin)
                                                  ,(* (let ((width (doom-modeline --font-width)))
                                                        (or (and (= width 1) 1)
                                                            (/ width (frame-char-width) 1.0)))
                                                      (string-width
                                                       (format-mode-line
                                                        (cons ""
                                                              '(:eval (doom-modeline-segment--major-mode))))))))))
                  (:eval (doom-modeline-segment--major-mode)))))

  (add-hook 'nov-mode-hook #'+nov-mode-setup))
#+END_SRC

*** Programming Languages
**** Open CAD
#+BEGIN_SRC elisp :tangle ../configs/.doom.d/packages.el
(package! scad-mode)
#+END_SRC

**** Go mode
Go mode is a mode for writing golang code. In order to get the mode to work properly, it requires some configuration. I found instructions for setting stuff on [[https://wmanger.com/articles/go-on-doom-emacs/][this]] blog and then adding ~gopls~ and ~golangci-lint~.

**** Vimrc
#+BEGIN_SRC elisp :tangle ../configs/.doom.d/packages.el
(package! vimrc-mode)
#+END_SRC

**** Graphviz
#+BEGIN_SRC elisp :tangle ../configs/.doom.d/packages.el
(package! graphviz-dot-mode)
#+END_SRC

#+BEGIN_SRC elisp :tangle ../configs/.doom.d/packages.el
(package! systemd)
#+END_SRC

** Fun
*** XKCD
#+BEGIN_SRC elisp :tangle ../configs/.doom.d/packages.el
;; Fun stuff
(package! xkcd)
#+END_SRC

*** Typewriter
Makes emacs sound like a typewriter.
#+BEGIN_SRC elisp :tangle ../configs/.doom.d/packages.el
(package! selectric-mode)
#+END_SRC

*** Games
**** steam
A package for accessing and organizing your steam library from within emacs
#+BEGIN_SRC elisp :tangle ../configs/.doom.d/packages.el
(package! steam)
#+END_SRC

**** 2048-game
#+BEGIN_SRC elisp :tangle ../configs/.doom.d/packages.el
(package! 2048-game)
#+END_SRC

**** mines
#+BEGIN_SRC elisp :tangle ../configs/.doom.d/packages.el
(package! mines)
#+END_SRC

**** minesweeper
#+BEGIN_SRC elisp :tangle ../configs/.doom.d/packages.el
(package! minesweeper)
#+END_SRC

**** sudoku
#+BEGIN_SRC elisp :tangle ../configs/.doom.d/packages.el
(package! sudoku)
#+END_SRC

**** threes
#+BEGIN_SRC elisp :tangle ../configs/.doom.d/packages.el
(package! threes)
#+END_SRC
**** Pacmacs
#+BEGIN_SRC elisp :tangle ../configs/.doom.d/packages.el
(package! pacmacs)
#+END_SRC

*** Fireplace
#+BEGIN_SRC elisp :tangle ../configs/.doom.d/packages.el
(package! fireplace)
#+END_SRC

** Experimental personal functions
#+BEGIN_SRC elisp
(defun print-point-position ()
  "Print the position of point to the message console."
  (interactive)
  (message (number-to-string (point))))

(map! :leader
      (:prefix-map ("a" . "Additional")
        (:desc "Point's position" "p" #'print-point-position)))
;;        (:prefix-map ("a" . "test2")
;;         (:prefix ("a" . "test")
;;          :desc "a test function to see if this works" "j" #'org-journal-new-entry
         ;; :desc "Search journal entry" "s" #'org-journal-search))))
;;
#+END_SRC

** Fixes
Here are some config fixes for issues I'm running into.

This issue is with some hook that is causing all my actions to fail its getting really annoying. I couldn't even use magit. Well now you're gone little guy, hope you're happy.
#+BEGIN_SRC elisp
(remove-hook! '(magit-mode-hook find-file-hook) #'forge-bug-reference-setup)
#+END_SRC

This package's git github repo recently changed and so the pinning information is wrong. I'm unpinning it for now so that things build correctly. Eventually this will get fixed and can be removed. This isn't a big risk since this package is not under active development so the no breaking changes should come any time soon.
#+BEGIN_SRC elisp :tangle ../configs/.doom.d/packages.el
(unpin! dired-git-info)
#+END_SRC
* Auto Tangle
The below allows this file to tangle and produce the output configuration files whenever the document is saved.

;; Local Variables:
;; eval: (add-hook 'after-save-hook (lambda () (org-babel-tangle)))
;; End:
