#+TITLE: MacOS Setup Config File
#+AUTHOR: Samuel Jackson
#+DESCRIPTION: This file creates scripts for setting up a new Mac machine.
#+STARTUP: overview num hidestars indent
#+PROPERTY: header-args :results silent :tangle "../scripts/macos/programs_install.sh" :tangle-mode (identity #o755)

* Scripts setup
Many scripts require some setup to make sure the dependencies are met. If a section makes its own file that shouldn't be written to by other sections, then those are not initialized here.
** programs_install.sh
Here we need to install brew and add some other package manager related packages to make sure everything installs smoothly.
#+begin_src sh
#!/bin/bash
#+end_src

Here we need to install brew to make sure everything installs smoothly. If brew is already installed we don't reinstall it since that is a pain.
#+begin_src sh
if ! command -v brew &> /dev/null
then
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    export PATH="/opt/homebrew/bin:${PATH}"
fi
#+end_src

Then we add ~mas~ which is the =Mac App Store= program which is used to install app store apps from the command line.
#+begin_src sh
brew tap buo/cask-upgrade
brew install mas
sudo softwareupdate --install-rosetta
#+end_src

*** Xcode
Xcode is the compiler for mac apps. It takes forever to download but it's good to have installed before it's actually needed.
#+begin_src sh
mas install 497799835 # Xcode
sudo xcodebuild -license accept
#+end_src

** configure_settings.sh
Just need to declare the executing program
#+begin_src sh :tangle ../scripts/macos/configure_settings.sh
#!/bin/bash
#+end_src

* Aliases
Since macos uses some aliases and environment values that are different from my standard sort of linux environments, this script sets up the local shell setup files so the system runs smoothly.
#+begin_src sh :tangle ../scripts/macos/make_aliases.sh
#!/bin/bash

echo "# When coreutils is installed,"                          >> ~/.shell_setup/aliases.local.sh
echo "# ls does as expected, but when"                         >> ~/.shell_setup/aliases.local.sh
echo "# core utils is not present,"                            >> ~/.shell_setup/aliases.local.sh
echo "# ls uses the MacOS flag of -G"                          >> ~/.shell_setup/aliases.local.sh
echo "# instead of --color."                                   >> ~/.shell_setup/aliases.local.sh
echo "#alias ls='ls -G -bF'"                                   >> ~/.shell_setup/aliases.local.sh
echo "unalias open"                                            >> ~/.shell_setup/aliases.local.sh
echo ""                                                        >> ~/.shell_setup/aliases.local.sh
echo "if type brew &>/dev/null; then"                          >> ~/.shell_setup/aliases.local.sh
echo "    FPATH=$(brew --prefix)/share/zsh-completions:$FPATH" >> ~/.shell_setup/aliases.local.sh
echo ""                                                        >> ~/.shell_setup/aliases.local.sh
echo "    autoload -Uz compinit"                               >> ~/.shell_setup/aliases.local.sh
echo "    compinit"                                            >> ~/.shell_setup/aliases.local.sh
echo "fi"                                                      >> ~/.shell_setup/aliases.local.sh
#+end_src

* Path
Since macos uses some aliases and environment values that are different from my standard sort of linux environments, this script sets up the local shell setup files so the system runs smoothly.
#+begin_src sh :tangle ../scripts/macos/make_path.sh
#!/bin/bash
echo 'export PATH="/opt/homebrew/bin:${PATH}"'
echo 'export PATH="$(brew --prefix)/opt/coreutils/libexec/gnubin:${PATH}"' >> ~/.shell_setup/path_setup.local.sh
#+end_src

* Applications
** Terminals
*** Iterm
Iterm is the best terminal on MacOS. This (for me) is primarily because mac has the stupid options button that replaces the alt key and this is one of the only terminals that interpret option key-cords correctly instead of creating some unicode glyph. I really hate this part of MacOS...
#+begin_src sh
brew install --cask iterm2
#+end_src

*** Alacritty
The default terminal I use on all other systems.
#+begin_src sh
brew install --cask alacritty
#+end_src

** Zoom
A popular video calling service.
#+begin_src sh
brew install --cask zoom
#+end_src

** VLC
This can play anything. The interface is ugly, but if it's a video file then VLC will play it.
#+begin_src sh
brew install --cask vlc
#+end_src

** Text editors
*** Emacs
Emacs is a lisp programming environment that's better known for it's text editing capabilities.
#+begin_src sh :tangle no
brew install --cask emacs
#+end_src

The standard emacs install that brew provides uses 27.2 but version 28 has a feature that compiles the elisp code to byte code which is too good to pass up!
#+begin_src sh
brew tap d12frosted/emacs-plus
brew install emacs-plus@28 --with-imagemagick --with-native-comp --with-dbus --with-modern-alecive-flatwoken-icon
#+end_src

Once emacs is installed, it should be added to the applications section.
#+begin_src sh :tangle ../scripts/macos/configure_settings.sh
ln -s /usr/local/opt/emacs-plus@28/Emacs.app /Applications
#+end_src

*** Sublime-text
A popular text editor. I don't use it much but I can try it later.
#+begin_src sh
brew install sublime-text
#+end_src

*** Brackets
A popular text editor. I don't use it much but I can try it later.
#+begin_src sh
brew install brackets
#+end_src

*** Atom
A popular text editor. I don't use it much but I can try it later.
#+begin_src sh
brew install atom
#+end_src

*** Visual studio code
A popular text editor. I don't use it much but I can try it later.
#+begin_src sh
brew install visual-studio-code
#+end_src

*** Intellij
Intellij is the industry standard IDE for java and similar languages.
#+begin_src sh
brew install --cask intellij-idea-ce
#+end_src

*** Goland
An intellij-like IDE (also made by jetbrains) for working with go.
#+begin_src sh
brew install --cask goland
#+end_src

*** Webstorm
A Jetbrains product for working with javascript
#+begin_src sh
brew install --cask webstorm
#+end_src

** Web Browsers
*** Chrome
Chrome is my usual standard choice for a web browser.
#+begin_src sh
brew install --cask google-chrome
#+end_src

*** Firefox
I've always found firefox to be slower than chrome but it is more open source so I like to use it once in a while.
#+begin_src sh
brew install --cask firefox
#+end_src

*** Brave
Brave browser is a privacy focused browser with good adblocking.
#+begin_src sh
brew install --cask brave-browser
#+end_src
*** Qutebrowser
Qutebrowser is a wonderful little web browser that incorporates vim style keybindings and modal tab management. It's missing plugins and a better adblocker but I still love it! There ARE plugins that provide similar functionality in chrome/firefox that I want to explore some more, but they've never been as fully functioning and as clean to use as my dear qutebrowser.
#+begin_src sh
brew install --cask qutebrowser
#+end_src

Qutebrowser has some weird issue that makes it unable to run out of the cask so this command allows it to work. Don't entirely understand it but that's the way life goes sometimes. After allowing it to run, the config file is aliased to the ~.qutebrowser~ folder that macos uses instead of the ~.config/qutebrowser~ folder.
#+begin_src sh :tangle ../scripts/macos/configure_settings.sh
sudo xattr -rd com.apple.quarantine /Applications/qutebrowser.app
ln -s ~/.config/qutebrowser/config.py ~/.qutebrowser/config.py
#+end_src

** Slack
Slack is a very popular tool for business messaging and communication.
#+begin_src sh
brew install --cask slack
#+end_src

** Gimp
Best open source image editor!
#+begin_src sh
brew install --cask gimp
#+end_src

** PGAdmin
A good gui for accessing postgres tables.
#+begin_src sh
brew install --cask pgadmin4
#+end_src

** Postman
Postman is an application for making http api requests to services.
#+begin_src sh
brew install --cask postman
#+end_src

* CLI tools
** Coreutils
The standard GNU utilities. Although these are provided with MacOS already, the ones included here should have the standard option flags which will make my life easier (for the most part...).
#+begin_src sh
brew install coreutils
#+end_src

** awscli
A CLI tool for accessing and using AWS resources.
#+begin_src sh
brew install awscli
#+end_src

Along with this, usually when using the aws CLI you also need to authenticate and hence use this:
#+begin_src sh
brew install aws-iam-authenticator
#+end_src

** tmux
Tmux is a terminal multiplexer and session daemon. It works really well for having your own set of desktops in the terminal itself.
#+begin_src sh
brew install tmux
#+end_src

** wget
Wget is a web downloader similar to curl. It gets used instead of curl in a couple of places so it's good to have installed.
#+begin_src sh
brew install wget
#+end_src

** HttPie
An alternative to curl and wget.
#+begin_src sh
brew install httpie
#+end_src

** sl
Sl is the steam locomotive program. Who doesn't like trains?
#+begin_src sh
brew install sl
#+end_src

** fd
Fd is a find-like utility.
#+begin_src sh
brew install fd
#+end_src

** ranger
Ranger is a terminal file manager. Nice to use when you need to manipulate files.
#+begin_src sh
brew install ranger
#+end_src

** pass
Pass is an open source package manager.
#+begin_src sh
brew install pass
#+end_src

** cmatrix
Cmatrix allows you to enter the (c)Matrix!
#+begin_src sh
brew install cmatrix
#+end_src

** pandoc
Pandoc is a converter that transpiles several different kinds of docs such as markdown into latex or Org into latex or wikix into latex... I mostly use it for turning org files into pdfs or wiki pages.
#+begin_src sh
brew install pandoc
#+end_src

** asciidoc
Converts asciidoc files into DocBook or HTML.
#+begin_src sh
brew install asciidoc
#+end_src

** htop
Htop is a terminal based process viewer and manager.
#+begin_src sh
brew install htop
#+end_src

** tldr
Tldr is a program that provides example usage for several common cli tools out there.
#+begin_src sh
brew install tldr
#+end_src

** jq
Jq is a cli tool for JSON reading and manipulation.
#+begin_src sh
brew install jq
#+end_src

** tty-clock
Tty-clock is a... clock, in the... tty.
#+begin_src sh
brew install tty-clock
#+end_src

** ffmpeg
Ffmpeg is a super powerful cli video and photo modifier.
#+begin_src sh
brew install ffmpeg
#+end_src

** pdftk
PDFtk is a utility function that allows you to combine PDFs together into a single PDF document.
#+begin_src sh
brew install pdftk-java
#+end_src

To use PDFtk, you simply need to run a command like the following
#+begin_src sh :tangle no
pdftk dir_of_files/* cat output "combined.pdf" # cat stands for for concatenate
#+end_src

** Shells
*** Bash
#+begin_src sh
brew install bash
brew install bash-completion
#+end_src
*** Zsh
#+begin_src sh
brew install zsh
brew install zsh-autosuggestions
brew install zsh-navigation-tools
brew install zsh-lovers
brew install zsh-syntax-highlighting
brew install zsh-completions
brew install zsh-you-should-use
#+end_src

There's a weird issue that causes zsh to show a warning when starting up. This fixes it.
#+begin_src sh :tangle ../scripts/macos/configure_settings.sh
sudo chmod -R 755 /usr/local/share
#+end_src

** Cmake
Used for vterm in emacs.
#+begin_src sh
brew install cmake
#+end_src

*** Ripgrep
A fast grep tool for finding files. Used in emacs.
#+begin_src sh
brew install ripgrep
#+end_src

*** Silver searcher
Another fast grep tool for finding files. Also used in emacs.
#+begin_src sh
brew install ag
#+end_src

** Ledger
Ledger is a CLI program for double-entry accounting. Neat!
#+begin_src sh
brew install ledger
#+end_src

** Cloc
Cloc is a program that counts lines of code in files.
#+begin_src sh
brew install cloc
#+end_src

** Sops
Tool for working with encrypted files and secrets.
#+begin_src sh
brew install sops
#+end_src

** k9 interface
Cli tool for interfacing with kubernetes
#+begin_src sh
brew install k9s
#+end_src

** RabbitMQ
A local viewer for the [[https://www.rabbitmq.com/][Rabbit MQ]] messaging system.
#+begin_src sh
brew install rabbitmq
#+end_src

** Pgcli
A tool for accessing postgresSQL databases from command line. Has some pretty neat auto-completion and syntax highlighting!
#+begin_src sh
brew install pgcli
#+end_src

** Nmap
A useful network scanner.
#+begin_src sh
brew install nmap
#+end_src

** Hstr
A history manager that provides suggestions of previous commands.
#+begin_src sh
brew install hstr
#+end_src

** Speedtest cli
When dealing with internet issues, it helps to be able to run a speed test from the command line.
#+begin_src sh
brew install speedtest_cli
#+end_src

** Z
A smart ~cd~.
#+begin_src sh
brew install z
#+end_src

* Utilities
** Postgresql
#+begin_src sh
brew install postgresql
brew install golang-migrate
#+end_src

** Docker
Docker is a tool for creating VMs to run software. Needed at many software companies.
#+begin_src sh
brew install --cask docker
#+end_src

** Lastpass
Lastpass is a tool for password management.
#+begin_src sh
brew install --cask lastpass
brew install lastpass-cli
#+end_src

** 1clipboard
1clipboard manages your clipboard history and access what you've copied before.
#+begin_src sh
brew install --cask 1clipboard
#+end_src

** Background-music
Background music is a nice program for managing the audio streams on your computer.
#+begin_src sh
brew install --cask background-music
#+end_src

** Amphetamine
Amphetamine is a program that keeps the computer awake without interaction from the user. Super convenient when installing programs or just watching something.
#+begin_src sh
mas install 937984704 # Amphetamine
#+end_src

Also install caffeine as backup
#+begin_src sh
brew install caffeine
#+end_src

** Dropbox
Dropbox is a file syncing service. I use it to manage my database of org files.
#+begin_src sh
brew install --cask dropbox
#+end_src

** Alphred
Alphred is a more customizable spotlight.
#+begin_src sh
brew install --cask alfred
#+end_src

** Go2shell
Allows you to open up a terminal in a particular folder from Finder.
#+begin_src sh
brew install --cask go2shell
#+end_src
** Spectacle
A tool for window snap management.
#+begin_src sh
brew install --cask spectacle
#+end_src
** VPN
*** TunnelBlick
Tunnel blick is a free OpenVPN client for MacOS. [[https://www.tunnelblick.net][homepage]].
#+begin_src sh
brew install --cask tunnelblick
#+end_src

*** AWS VPN
AWS VPN client allows you to connect to the AWS vpn which is
#+begin_src sh
brew install --cask --cask aws-vpn-client

#+end_src

** GNU plot
GNU plot is a tool for creating graphs and other visuals. Used by emacs
#+begin_src sh
brew install gnuplot
#+end_src
** Graphviz
A tool for converting certain types of files into graphics.
#+begin_src sh
brew install graphviz
#+end_src

** Kubernetes
Kubernetes command line interface
#+begin_src sh
brew install kubernetes-cli
#+end_src

*** Minikube
Runs a kubernetes cluster locally.
#+begin_src sh
brew install minikube
#+end_src

Then install the hyperkit drivers so minikube can use more memory.
#+begin_src sh
brew install hyperkit
#+end_src

To use hyperkit, start minikube as follows:
#+begin_src sh :tangle no
minikube start --memory='4g' --cpus='2' --driver='hyperkit'
#+end_src


*** Helm
To use kubernetes, we also need to have helm installed. And add some of the more common helm plugins for good measure.
#+begin_src sh
brew install helm
helm plugin install https://github.com/jkroepke/helm-secrets --version v3.11.0
helm plugin install https://github.com/rimusz/helm-tiller
#+end_src

*** EKS
Then this tool is used to create clusters on Amazon EKS. It could go up with the AWS CLI, but it's more related to kubernetes clusters.
#+begin_src sh
brew install eksctl
#+end_src

*** Skaffold
Skaffold is a program for running persistent updating local testing in kubernetes.
#+begin_src sh
brew install skaffold
#+end_src

*** Kustomize
Kustomize is a tool to help build kubernetes applications.
#+begin_src sh
brew install kustomize
#+end_src

** Localstack
Local stack is an AWS emulation program that allows you to run and test AWS integration code from your local computer. [[https://docs.localstack.cloud/overview/][Link to the docs]].
#+begin_src sh
pip3 install --user localstack
pip3 install --user aws-local
#+end_src

** Aspell
A good spellchecking backend. Used by emacs.
#+begin_src sh
brew install aspell
#+end_src

** Android
Needed to use adb and important tools for working with android devices.
#+begin_src sh
brew install android-sdk
brew install android-platform-tools
#+end_src

Here are other tools for working with android devices.
#+begin_src sh
brew install lsusb
#+end_src

** Editor config
Another package for Emacs.
#+begin_src sh
brew install editorconfig
#+end_src
** Direnv tool
Load/unload environment variables based on $PWD.
#+begin_src sh
brew install direnv
#+end_src

** Programming languages
*** Go
A clean simple little language. See the [[https://go.dev][golang]] website.
#+begin_src sh
brew install go
#+end_src

Go's language server for editors like emacs or vs-code.
#+begin_src sh
brew install gopls
#+end_src

And the linter that goes along with it.
#+begin_src sh
brew install golangci-lint
#+end_src
*** Java
For formatting java code in emacs.
#+begin_src sh
brew install clang-format
#+end_src
*** Kotlin
Kotlin is a JVM language with lots of nice features. Essentially what you would hope java to be.
#+begin_src sh
brew install ktlint
#+end_src

*** Python
In Emacs, python uses a language foratter called black:
#+begin_src sh
brew install black
#+end_src
*** Haskell
Install haskell compiler and its language server. Haskell is useful for scripting some things.
#+begin_src sh
brew install ghc
brew install haskell-language-server
brew install cabal-install
#+end_src
*** Common Lisp
For emacs.
#+begin_src sh
brew install sbcl
#+end_src

*** Python
When using python, being able to use environments is a must due to the awkward package management.
#+begin_src sh
brew install pyenv
#+end_src

*** Racket
Racket is a popular lisp language.
#+begin_src sh
brew install --cask racket
#+end_src

*** Rust
Rust is up-and-coming so may as well have all the stuff already available.

First install the compiler and a completion package for it.
#+begin_src sh
brew install rust
brew install rustc-completion
#+end_src

Then install the rust toolchain.
#+begin_src sh
brew install rustup-init
#+end_src

And then finally an analyzer to measure code performance.
#+begin_src
brew install rust-analyzer
#+end_src

*** Html
Great set of HTML tools.
#+begin_src sh
brew install tidy-html5
#+end_src

*** LaTeX
The whole latex environment. It's a big package but there should be enough space on most machines that it won't matter.
#+begin_src sh
brew install texlive
#+end_src
*** Shell
Various tools for making shell scripts.
#+begin_src sh
brew install shfmt
brew install shellcheck
#+end_src
*** Markdown
Grip is nice markdown viewer so you can see what you've written before publishing.
#+begin_src sh
brew install grip
#+end_src

*** Web
Npm is the main package manager for anything and everything javascript. Better have it installed!
#+begin_src sh
brew install npm
#+end_src

Nvm for managing node versions.
#+begin_src sh
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
#+end_src

Once npm is installed, it can be used to install packages useful for web development.
#+begin_src sh
npm -g install js-beautify
npm -g install stylelint
#+end_src

* Full system install script
When I need to install on a whole system, I want to have a single script I can run to install basically everything and not need to worry about which scripts to run first or in what order.
#+begin_src sh :tangle ../scripts/macos/full_system_install.sh
#!/bin/bash
# This file has been generated using org tangle. To modify, please see the org file.
#+end_src

TODO prompt to ask about installing doom and fonts. Those are both really long running processes that may not be immediately wanted.
#+begin_src sh :tangle ../scripts/macos/full_system_install.sh
#+end_src

First we install all the packages. Partly because this is the most intensive part and partly because this ensures that any following scripts have their dependencies installed.
#+begin_src sh :tangle ../scripts/macos/full_system_install.sh
./programs_install.sh
#+end_src

Next we install all the config files. This way they're present when things are installed. If this came later, then some of the config files may be created ahead of time which causes problems with symbolically linking to my own configs.
#+begin_src sh :tangle ../scripts/macos/full_system_install.sh
../configs_install.sh
#+end_src

Next we need make sure macos specific aliases are present.
#+begin_src sh :tangle ../scripts/macos/full_system_install.sh
./make_aliases.sh
#+end_src

Next comes oh-my-zsh since a clean terminal is so important.
#+begin_src sh :tangle ../scripts/macos/full_system_install.sh
../oh-my-zsh_install.sh
#+end_src

Next comes my NPM settings.
#+begin_src sh :tangle ../scripts/macos/full_system_install.sh
../npm_install.sh
#+end_src

Following that comes the pass plugins so I can use my password manager.
#+begin_src sh :tangle ../scripts/macos/full_system_install.sh
../pass-addons_install.sh
#+end_src

And finally we fix correct any MacOS specific issues.
#+begin_src sh :tangle ../scripts/macos/full_system_install.sh
./configure_settings.sh
#+end_src

* Local Variables
The below allows this file to tangle and produce the output RC file whenever the document is saved.

;; Local Variables:
;; eval: (add-hook 'after-save-hook (lambda () (org-babel-tangle)))
;; End:
